"""Shared AWS configuration for MTH data pipeline scripts."""

import json
import os
from pathlib import Path

import boto3

PROFILE_NAME = os.environ.get("AWS_PROFILE", "move-to-happy")
REGION = "us-east-1"


def get_session() -> boto3.Session:
    """Create a boto3 session using the MTH AWS SSO profile."""
    return boto3.Session(profile_name=PROFILE_NAME, region_name=REGION)


def load_pipeline_config() -> dict:
    """Load pipeline config generated by script 02."""
    config_path = (
        Path(__file__).resolve().parent.parent / "data" / "pipeline_config.json"
    )
    with open(config_path) as f:
        return json.load(f)
